apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prooftag-qr-data
  namespace: qr-core
  labels:
    app: prooftag-qr
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prooftag-qr-model-cache
  namespace: qr-core
  labels:
    app: prooftag-qr
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 80Gi

