from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
)

metadata = MetaData()

runs = Table(
    "runs",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("completed_at", DateTime(timezone=True)),
    Column("status", String(20), nullable=False),
    Column("backend", String(40), nullable=False),
    Column("prompt", Text, nullable=False),
    Column("payload_hash", String(64), nullable=False),
    Column("seed", Integer, nullable=False),
    Column("attempts", Integer, nullable=False, default=0),
    Column("image_path", Text),
    Column("qr_version", Integer),
    Column("scan_pass_rate", Float),
    Column("exact_payload_match", Boolean),
    Column("module_error_rate", Float),
    Column("generation_ms", Float),
    Column("validation_ms", Float),
    Column("total_ms", Float),
    Column("error", Text),
    Index("idx_runs_created_at", "created_at"),
    Index("idx_runs_status", "status"),
)

validations = Table(
    "validations",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("run_id", String(36), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False),
    Column("decoder", String(40), nullable=False),
    Column("scenario", String(80), nullable=False),
    Column("success", Boolean, nullable=False),
    Column("exact_payload_match", Boolean, nullable=False),
    Column("latency_ms", Float, nullable=False),
    Column("decoded_hash", String(64)),
    Column("parameters", JSON, nullable=False),
    Index("idx_validations_run", "run_id"),
    Index("idx_validations_dimensions", "decoder", "scenario"),
)

attempts = Table(
    "attempts",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("run_id", String(36), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False),
    Column("attempt", Integer, nullable=False),
    Column("seed", Integer, nullable=False),
    Column("generation_ms", Float, nullable=False),
    Column("validation_ms", Float, nullable=False),
    Column("scan_pass_rate", Float, nullable=False),
    Column("module_error_rate", Float, nullable=False),
    Column("accepted", Boolean, nullable=False),
    UniqueConstraint("run_id", "attempt", name="uq_attempt_run_number"),
)

quality_metrics = Table(
    "quality_metrics",
    metadata,
    Column("run_id", String(36), ForeignKey("runs.id", ondelete="CASCADE"), primary_key=True),
    Column("name", String(100), primary_key=True),
    Column("value", Float, nullable=False),
)

physical_validations = Table(
    "physical_validations",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("run_id", String(36), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("device", String(100), nullable=False),
    Column("operating_system", String(100), nullable=False),
    Column("scanner", String(100), nullable=False),
    Column("print_profile", String(100), nullable=False),
    Column("material", String(100), nullable=False),
    Column("size_mm", Float),
    Column("lighting", String(100), nullable=False),
    Column("distance_cm", Float),
    Column("angle_degrees", Float),
    Column("scan_latency_ms", Float),
    Column("outcome", String(30), nullable=False),
    Column("decoded_hash", String(64)),
    Column("notes", Text, nullable=False),
    Index("idx_physical_run", "run_id"),
    Index("idx_physical_dimensions", "device", "print_profile", "material", "outcome"),
)
