from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
)

metadata = MetaData()

runs = Table(
    "runs",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("completed_at", DateTime(timezone=True)),
    Column("status", String(20), nullable=False),
    Column("backend", String(40), nullable=False),
    Column("prompt", Text, nullable=False),
    Column("payload_hash", String(64), nullable=False),
    Column("seed", Integer, nullable=False),
    Column("selected_variant", String(100)),
    Column("selection_mode", String(20), nullable=False, default="delivery"),
    Column("stage1_reused", Boolean, nullable=False, default=False),
    Column("stage1_source_run_id", String(36)),
    Column("attempts", Integer, nullable=False, default=0),
    Column("image_path", Text),
    Column("qr_version", Integer),
    Column("scan_pass_rate", Float),
    Column("exact_payload_match", Boolean),
    Column("module_error_rate", Float),
    Column("generation_ms", Float),
    Column("validation_ms", Float),
    Column("total_ms", Float),
    Column("error", Text),
    Column("provenance", JSON, nullable=False, default=dict),
    Index("idx_runs_created_at", "created_at"),
    Index("idx_runs_status", "status"),
)

validations = Table(
    "validations",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("run_id", String(36), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False),
    Column("decoder", String(40), nullable=False),
    Column("scenario", String(80), nullable=False),
    Column("success", Boolean, nullable=False),
    Column("exact_payload_match", Boolean, nullable=False),
    Column("latency_ms", Float, nullable=False),
    Column("decoded_hash", String(64)),
    Column("parameters", JSON, nullable=False),
    Index("idx_validations_run", "run_id"),
    Index("idx_validations_dimensions", "decoder", "scenario"),
)

attempts = Table(
    "attempts",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("run_id", String(36), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False),
    Column("attempt", Integer, nullable=False),
    Column("seed", Integer, nullable=False),
    Column("generation_ms", Float, nullable=False),
    Column("validation_ms", Float, nullable=False),
    Column("scan_pass_rate", Float, nullable=False),
    Column("module_error_rate", Float, nullable=False),
    Column("accepted", Boolean, nullable=False),
    UniqueConstraint("run_id", "attempt", name="uq_attempt_run_number"),
)

quality_metrics = Table(
    "quality_metrics",
    metadata,
    Column("run_id", String(36), ForeignKey("runs.id", ondelete="CASCADE"), primary_key=True),
    Column("name", String(100), primary_key=True),
    Column("value", Float, nullable=False),
)

physical_validations = Table(
    "physical_validations",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("run_id", String(36), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("device", String(100), nullable=False),
    Column("operating_system", String(100), nullable=False),
    Column("scanner", String(100), nullable=False),
    Column("print_profile", String(100), nullable=False),
    Column("material", String(100), nullable=False),
    Column("size_mm", Float),
    Column("lighting", String(100), nullable=False),
    Column("distance_cm", Float),
    Column("angle_degrees", Float),
    Column("scan_latency_ms", Float),
    Column("outcome", String(30), nullable=False),
    Column("decoded_hash", String(64)),
    Column("notes", Text, nullable=False),
    Index("idx_physical_run", "run_id"),
    Index("idx_physical_dimensions", "device", "print_profile", "material", "outcome"),
)

lab_campaigns = Table(
    "lab_campaigns",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("name", String(200), nullable=False),
    Column("status", String(30), nullable=False),
    Column("payload_hash", String(64), nullable=False),
    Column("specification", JSON, nullable=False),
    Column("total_trials", Integer, nullable=False, default=0),
    Column("completed_trials", Integer, nullable=False, default=0),
    Column("accepted_trials", Integer, nullable=False, default=0),
    Column("error", Text),
    Index("idx_lab_campaigns_created_at", "created_at"),
    Index("idx_lab_campaigns_status", "status"),
)

lab_trials = Table(
    "lab_trials",
    metadata,
    Column("id", String(36), primary_key=True),
    Column(
        "campaign_id",
        String(36),
        ForeignKey("lab_campaigns.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("completed_at", DateTime(timezone=True)),
    Column("prompt_id", String(100), nullable=False),
    Column("method_id", String(100), nullable=False),
    Column("seed", Integer, nullable=False),
    Column("status", String(30), nullable=False),
    Column("generation_run_id", String(36), ForeignKey("runs.id", ondelete="SET NULL")),
    Column("configuration", JSON, nullable=False),
    Column("error", Text),
    UniqueConstraint(
        "campaign_id",
        "prompt_id",
        "method_id",
        "seed",
        name="uq_lab_trial_dimensions",
    ),
    Index("idx_lab_trials_campaign", "campaign_id"),
    Index("idx_lab_trials_status", "status"),
)

lab_ratings = Table(
    "lab_ratings",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column(
        "trial_id",
        String(36),
        ForeignKey("lab_trials.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    ),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("aesthetic_score", Integer),
    Column("aesthetic_ok", Boolean),
    Column("human_scan_result", String(20), nullable=False, default="not_tested"),
    Column("human_scan_attempts", Integer, nullable=False, default=0),
    Column("human_scan_successes", Integer, nullable=False, default=0),
    Column("human_scan_device", String(200), nullable=False, default=""),
    Column("prompt_fidelity_score", Integer),
    Column("qr_discretion_score", Integer),
    Column("overall_score", Integer),
    Column("favorite", Boolean, nullable=False, default=False),
    Column("notes", Text, nullable=False, default=""),
    Index("idx_lab_ratings_trial", "trial_id"),
)
